# Generated by Django 4.2.11 on 2024-04-22 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("first_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AcessRecord",
            new_name="AccessRecord",
        ),
        migrations.RenameField(
            model_name="webpage",
            old_name="tipic",
            new_name="topic",
        ),
    ]
